jira-integration/core/objects/Account/fields/JIRA_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Id__c</fullName>
    <externalId>true</externalId>
    <label>JIRA Project Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

jira-integration/core/objects/Account/fields/JIRA_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Key__c</fullName>
    <externalId>true</externalId>
    <label>JIRA Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/project/JiraProjectController.cls
public class JiraProjectController {
    public Id accId {get;set;}
    public Account acc {get;set;}
    
    public JiraProjectController(ApexPages.StandardController controller) {
        accId = controller.getRecord().Id;
        acc = [SELECT Id, Name, JIRA_Project_Id__c, JIRA_Project_Key__c FROM Account WHERE Id =: accId];
    }
    
    public PageReference createProject(){
        JIRAProjectHelper.createOrUpdateProject(acc);
        update acc;
        return new PageReference('/'+ accId);
    }
}