jira-integration/core/objects/Account/fields/JIRA_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Key__c</fullName>
    <externalId>true</externalId>
    <label>JIRA Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/JIRA_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Name__c</fullName>
    <label>JIRA Project Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/project/JIRAProjectMapping.cls
public with sharing class JIRAProjectMapping {

    public static JIRAProjectJSON mapAccountToProject(Account acc, String projectLeadId){
        JIRAProjectJSON json = new JIRAProjectJSON();
        json.name = acc.JIRA_Project_Name__c;
        //@TODO unhardcode
        if(String.isNotBlank(projectLeadId)){
            json.leadAccountId = projectLeadId;
        }
        json.projectTypeKey = 'software';
        json.key = acc.JIRA_Project_Key__c;

        return json;
    }
}