force-app/main/default/objects/Opportunity/fields/JIRA_Fix_Version_Name__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Fix_Version_Name__c</fullName>
    <label>JIRA Fix Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/JIRA_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Id__c</fullName>
    <formula>Account.JIRA_Project_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JIRA Project Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/JIRA_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Version_Id__c</fullName>
    <externalId>true</externalId>
    <label>JIRA Version Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/version/JIRAVersionMapping.cls
public with sharing class JIRAVersionMapping {

    public static JIRAVersionJSON mapOpportunityToVersion(Opportunity opp){
        JIRAVersionJSON version = new JIRAVersionJSON();

        version.name = opp.JIRA_Fix_Version_Name__c;
        version.id = opp.JIRA_Version_Id__c;
        version.description = opp.Name;
        version.projectId = Integer.valueOf(opp.JIRA_Project_Id__c);
        return version;
    }


    public static Opportunity mapVersionToOpportunity(JIRAVersionJSON version, Opportunity opp){
        opp.JIRA_Version_Id__c = String.valueOf(version.id);
        return opp;
    }
}